import { Instructor } from "./instructor.model";

export class RealWorkoutSchedule {
  id: number;
  currentParticipantNumber: number;
  maxParticipantNumber: number;
  startDate: Date;
  endDate: Date;
  workoutTypeId: number;
  workoutTypeName: string;
  intensity: string;
  instructorId: number;
  instructorName: string;
  instructorNameShort: string;

  constructor(data: RealWorkout) {
    this.id = data.id,
    this.currentParticipantNumber = data.currentParticipantNumber,
    this.maxParticipantNumber = data.maxParticipantNumber,
    this.startDate = new Date(data.date + ' ' + data.startTime),
    this.endDate = new Date(data.date + ' ' + data.endTime),
    this.workoutTypeId = data.workoutType.id,
    this.workoutTypeName = data.workoutType.name,
    this.intensity = data.workoutType.intensity,
    this.instructorId = data.instructor.id,
    this.instructorName = data.instructor.firstName + ' ' + data.instructor.lastName,
    this.instructorNameShort = data.instructor.firstName.charAt(0) + '. ' + data.instructor.lastName
  }
}

export interface RealWorkout {
  id: number;
  currentParticipantNumber: number;
  maxParticipantNumber: number;
  startTime: string;
  endTime: string;
  date: string;
  isAutoGenerated?: boolean;
  workoutType: { id: number, name: string, intensity: string };
  instructor: Instructor;
}