import { Instructor } from "./instructor.model";

export class RealWorkout {
  id: number;
  currentParticipantNumber: number;
  maxParticipantNumber: number;
  startTime: string;
  endTime: string;
  date: string;
  isAutoGenerated?: boolean;
  workoutType?: { id: number, name: string, description: string, intensity: string };
  instructor?: Instructor;

  constructor(data: {
    id: number,
    currentParticipantNumber: number,
    maxParticipantNumber: number,
    startTime: string,
    endTime: string,
    date: string,
    isAutoGenerated?: boolean,
    workoutType?: { id: number, name: string, description: string, intensity: string },
    instructor?: Instructor
  }) {
    this.id = data.id,
    this.currentParticipantNumber = data.currentParticipantNumber,
    this.maxParticipantNumber = data.maxParticipantNumber,
    this.startTime = data.startTime,
    this.endTime = data.endTime,
    this.date = data.date,
    this.isAutoGenerated = data.isAutoGenerated,
    this.workoutType = data.workoutType,
    this.instructor = data.instructor
  }
}