using MediatR;

namespace WorkoutReservation.Application.Features.RepetitiveWorkouts.Commands.GenerateUpcomingWorkoutTimetable
{
    public class GenerateUpcomingWorkoutTimetableCommand : IRequest
    {
        public bool IsAutoGenerated { get; set; }
    }
}
