using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WorkoutReservation.Infrastructure.Migrations
{
    public partial class SeparateRealWorkoutsAndRepetitiveWorkouts : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_BaseWorkouts_Instructors_InstructorId",
                schema: "WorkoutReservation",
                table: "BaseWorkouts");

            migrationBuilder.DropForeignKey(
                name: "FK_BaseWorkouts_WorkoutTypes_WorkoutTypeId",
                schema: "WorkoutReservation",
                table: "BaseWorkouts");

            migrationBuilder.DropForeignKey(
                name: "FK_Reservations_BaseWorkouts_RealWorkoutId",
                schema: "WorkoutReservation",
                table: "Reservations");

            migrationBuilder.DropPrimaryKey(
                name: "PK_BaseWorkouts",
                schema: "WorkoutReservation",
                table: "BaseWorkouts");

            migrationBuilder.DropColumn(
                name: "CurrentParticipantNumber",
                schema: "WorkoutReservation",
                table: "BaseWorkouts");

            migrationBuilder.DropColumn(
                name: "Date",
                schema: "WorkoutReservation",
                table: "BaseWorkouts");

            migrationBuilder.DropColumn(
                name: "Discriminator",
                schema: "WorkoutReservation",
                table: "BaseWorkouts");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                schema: "WorkoutReservation",
                table: "BaseWorkouts");

            migrationBuilder.RenameTable(
                name: "BaseWorkouts",
                schema: "WorkoutReservation",
                newName: "RepetitiveWorkouts",
                newSchema: "WorkoutReservation");

            migrationBuilder.RenameIndex(
                name: "IX_BaseWorkouts_WorkoutTypeId",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts",
                newName: "IX_RepetitiveWorkouts_WorkoutTypeId");

            migrationBuilder.RenameIndex(
                name: "IX_BaseWorkouts_InstructorId",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts",
                newName: "IX_RepetitiveWorkouts_InstructorId");

            migrationBuilder.AlterColumn<int>(
                name: "WorkoutTypeId",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");

            migrationBuilder.AlterColumn<int>(
                name: "InstructorId",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");

            migrationBuilder.AlterColumn<string>(
                name: "DayOfWeek",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_RepetitiveWorkouts",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts",
                column: "Id");

            migrationBuilder.CreateTable(
                name: "RealWorkouts",
                schema: "WorkoutReservation",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Date = table.Column<DateTime>(type: "datetime2", nullable: false),
                    StartTime = table.Column<TimeSpan>(type: "time", nullable: false),
                    EndTime = table.Column<TimeSpan>(type: "time", nullable: false),
                    MaxParticipantNumber = table.Column<int>(type: "int", nullable: false),
                    CurrentParticipantNumber = table.Column<int>(type: "int", nullable: false),
                    IsAutoGenerated = table.Column<bool>(type: "bit", nullable: false),
                    WorkoutTypeId = table.Column<int>(type: "int", nullable: true),
                    InstructorId = table.Column<int>(type: "int", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    LastModifiedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LastModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RealWorkouts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RealWorkouts_Instructors_InstructorId",
                        column: x => x.InstructorId,
                        principalSchema: "WorkoutReservation",
                        principalTable: "Instructors",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_RealWorkouts_WorkoutTypes_WorkoutTypeId",
                        column: x => x.WorkoutTypeId,
                        principalSchema: "WorkoutReservation",
                        principalTable: "WorkoutTypes",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_RealWorkouts_InstructorId",
                schema: "WorkoutReservation",
                table: "RealWorkouts",
                column: "InstructorId");

            migrationBuilder.CreateIndex(
                name: "IX_RealWorkouts_WorkoutTypeId",
                schema: "WorkoutReservation",
                table: "RealWorkouts",
                column: "WorkoutTypeId");

            migrationBuilder.AddForeignKey(
                name: "FK_RepetitiveWorkouts_Instructors_InstructorId",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts",
                column: "InstructorId",
                principalSchema: "WorkoutReservation",
                principalTable: "Instructors",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_RepetitiveWorkouts_WorkoutTypes_WorkoutTypeId",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts",
                column: "WorkoutTypeId",
                principalSchema: "WorkoutReservation",
                principalTable: "WorkoutTypes",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Reservations_RealWorkouts_RealWorkoutId",
                schema: "WorkoutReservation",
                table: "Reservations",
                column: "RealWorkoutId",
                principalSchema: "WorkoutReservation",
                principalTable: "RealWorkouts",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_RepetitiveWorkouts_Instructors_InstructorId",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts");

            migrationBuilder.DropForeignKey(
                name: "FK_RepetitiveWorkouts_WorkoutTypes_WorkoutTypeId",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts");

            migrationBuilder.DropForeignKey(
                name: "FK_Reservations_RealWorkouts_RealWorkoutId",
                schema: "WorkoutReservation",
                table: "Reservations");

            migrationBuilder.DropTable(
                name: "RealWorkouts",
                schema: "WorkoutReservation");

            migrationBuilder.DropPrimaryKey(
                name: "PK_RepetitiveWorkouts",
                schema: "WorkoutReservation",
                table: "RepetitiveWorkouts");

            migrationBuilder.RenameTable(
                name: "RepetitiveWorkouts",
                schema: "WorkoutReservation",
                newName: "BaseWorkouts",
                newSchema: "WorkoutReservation");

            migrationBuilder.RenameIndex(
                name: "IX_RepetitiveWorkouts_WorkoutTypeId",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                newName: "IX_BaseWorkouts_WorkoutTypeId");

            migrationBuilder.RenameIndex(
                name: "IX_RepetitiveWorkouts_InstructorId",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                newName: "IX_BaseWorkouts_InstructorId");

            migrationBuilder.AlterColumn<int>(
                name: "WorkoutTypeId",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                type: "int",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "InstructorId",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                type: "int",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "DayOfWeek",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AddColumn<int>(
                name: "CurrentParticipantNumber",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "Date",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Discriminator",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                type: "bit",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_BaseWorkouts",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_BaseWorkouts_Instructors_InstructorId",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                column: "InstructorId",
                principalSchema: "WorkoutReservation",
                principalTable: "Instructors",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_BaseWorkouts_WorkoutTypes_WorkoutTypeId",
                schema: "WorkoutReservation",
                table: "BaseWorkouts",
                column: "WorkoutTypeId",
                principalSchema: "WorkoutReservation",
                principalTable: "WorkoutTypes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Reservations_BaseWorkouts_RealWorkoutId",
                schema: "WorkoutReservation",
                table: "Reservations",
                column: "RealWorkoutId",
                principalSchema: "WorkoutReservation",
                principalTable: "BaseWorkouts",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
