using WorkoutReservation.Domain.Common;

namespace WorkoutReservation.Domain.Entities;

public class RealWorkout : BaseWorkout
{
    public DateOnly Date { get; set; }
    public int CurrentParticipantNumber { get; set; }
    public bool IsAutoGenerated { get; set; }

    public ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}
