using WorkoutReservation.Domain.Common;

namespace WorkoutReservation.Domain.Entities.Workout
{
    public class ParticularWorkout : BaseWorkout
    {
        public DateOnly Date { get; set; }
        public int CurrentParticipianNumber { get; set; }
        public bool IsAutoGenerated { get; set; }
    }
}
