using WorkoutReservation.Domain.Entities;
using WorkoutReservation.Domain.Enums;

namespace WorkoutReservation.Infrastructure.Authorization;

internal static class RolePermissionMatrix
{
    public static IEnumerable<ApplicationRolePermission> Create()
    {
        return new List<ApplicationRolePermission>
        {
            new(ApplicationRole.SystemAdministrator, Permission.CreateInstructor),
            new(ApplicationRole.SystemAdministrator, Permission.UpdateInstructor),
            new(ApplicationRole.SystemAdministrator, Permission.DeleteInstructor),
            new(ApplicationRole.SystemAdministrator, Permission.CreateWorkoutType),
            new(ApplicationRole.SystemAdministrator, Permission.UpdateWorkoutType),
            new(ApplicationRole.SystemAdministrator, Permission.DeleteWorkoutType),
            new(ApplicationRole.SystemAdministrator, Permission.GetAllWorkoutTypeTags),
            new(ApplicationRole.SystemAdministrator, Permission.CreateWorkoutTypeTag),
            new(ApplicationRole.SystemAdministrator, Permission.UpdateWorkoutTypeTag),
            new(ApplicationRole.SystemAdministrator, Permission.DeleteWorkoutTypeTag),
            new(ApplicationRole.SystemAdministrator, Permission.GetRealWorkoutDetails),
            new(ApplicationRole.SystemAdministrator, Permission.CreateRealWorkout),
            new(ApplicationRole.SystemAdministrator, Permission.UpdateRealWorkout),
            new(ApplicationRole.SystemAdministrator, Permission.DeleteRealWorkout),
            new(ApplicationRole.SystemAdministrator, Permission.GetRepetitiveWorkouts),
            new(ApplicationRole.SystemAdministrator, Permission.CreateRepetitiveWorkout),
            new(ApplicationRole.SystemAdministrator, Permission.UpdateRepetitiveWorkout),
            new(ApplicationRole.SystemAdministrator, Permission.DeleteRepetitiveWorkout),
            new(ApplicationRole.SystemAdministrator, Permission.DeleteAllRepetitiveWorkouts),
            new(ApplicationRole.SystemAdministrator, Permission.GenerateNewUpcomingWeek),
            new(ApplicationRole.SystemAdministrator, Permission.CanSeeApplicationStatistics),
            new(ApplicationRole.SystemAdministrator, Permission.GetOwnReservations),
            new(ApplicationRole.SystemAdministrator, Permission.GetAllReservations),
            new(ApplicationRole.SystemAdministrator, Permission.GetOwnReservationDetails),
            new(ApplicationRole.SystemAdministrator, Permission.GetSomeoneReservationDetails),
            new(ApplicationRole.SystemAdministrator, Permission.CreateReservation),
            new(ApplicationRole.SystemAdministrator, Permission.CancelReservation),
            new(ApplicationRole.SystemAdministrator, Permission.UpdateReservation),
            new(ApplicationRole.SystemAdministrator, Permission.GetAllUsers),
            new(ApplicationRole.SystemAdministrator, Permission.SetUserRole),
            new(ApplicationRole.SystemAdministrator, Permission.DeleteUserAccount),
            new(ApplicationRole.SystemAdministrator, Permission.OpenAdministrationPage),
            new(ApplicationRole.SystemAdministrator, Permission.CanSeeAdministrativeContent),
            new(ApplicationRole.SystemAdministrator, Permission.GetWorkoutTypes),

            new(ApplicationRole.BusinessAdministrator, Permission.CreateInstructor),
            new(ApplicationRole.BusinessAdministrator, Permission.UpdateInstructor),
            new(ApplicationRole.BusinessAdministrator, Permission.DeleteInstructor),
            new(ApplicationRole.BusinessAdministrator, Permission.CreateWorkoutType),
            new(ApplicationRole.BusinessAdministrator, Permission.UpdateWorkoutType),
            new(ApplicationRole.BusinessAdministrator, Permission.DeleteWorkoutType),
            new(ApplicationRole.BusinessAdministrator, Permission.GetAllWorkoutTypeTags),
            new(ApplicationRole.BusinessAdministrator, Permission.CreateWorkoutTypeTag),
            new(ApplicationRole.BusinessAdministrator, Permission.UpdateWorkoutTypeTag),
            new(ApplicationRole.BusinessAdministrator, Permission.DeleteWorkoutTypeTag),
            new(ApplicationRole.BusinessAdministrator, Permission.GetRealWorkoutDetails),
            new(ApplicationRole.BusinessAdministrator, Permission.CreateRealWorkout),
            new(ApplicationRole.BusinessAdministrator, Permission.UpdateRealWorkout),
            new(ApplicationRole.BusinessAdministrator, Permission.DeleteRealWorkout),
            new(ApplicationRole.BusinessAdministrator, Permission.GetRepetitiveWorkouts),
            new(ApplicationRole.BusinessAdministrator, Permission.CreateRepetitiveWorkout),
            new(ApplicationRole.BusinessAdministrator, Permission.UpdateRepetitiveWorkout),
            new(ApplicationRole.BusinessAdministrator, Permission.DeleteRepetitiveWorkout),
            new(ApplicationRole.BusinessAdministrator, Permission.DeleteAllRepetitiveWorkouts),
            new(ApplicationRole.BusinessAdministrator, Permission.CanSeeApplicationStatistics),
            new(ApplicationRole.BusinessAdministrator, Permission.GetAllReservations),
            new(ApplicationRole.BusinessAdministrator, Permission.GetSomeoneReservationDetails),
            new(ApplicationRole.BusinessAdministrator, Permission.UpdateReservation),
            new(ApplicationRole.BusinessAdministrator, Permission.GetAllUsers),
            new(ApplicationRole.BusinessAdministrator, Permission.SetUserRole),
            new(ApplicationRole.BusinessAdministrator, Permission.DeleteOwnAccount),
            new(ApplicationRole.BusinessAdministrator, Permission.OpenAdministrationPage),
            new(ApplicationRole.BusinessAdministrator, Permission.CanSeeAdministrativeContent),
            new(ApplicationRole.BusinessAdministrator, Permission.GetWorkoutTypes),
            
            new(ApplicationRole.Manager, Permission.GetAllWorkoutTypeTags),
            new(ApplicationRole.Manager, Permission.GetRealWorkoutDetails),
            new(ApplicationRole.Manager, Permission.UpdateRealWorkout),
            new(ApplicationRole.Manager, Permission.GetRepetitiveWorkouts),
            new(ApplicationRole.Manager, Permission.GetOwnReservations),
            new(ApplicationRole.Manager, Permission.GetAllReservations),
            new(ApplicationRole.Manager, Permission.GetOwnReservationDetails),
            new(ApplicationRole.Manager, Permission.GetSomeoneReservationDetails),
            new(ApplicationRole.Manager, Permission.CreateReservation),
            new(ApplicationRole.Manager, Permission.CancelReservation),
            new(ApplicationRole.Manager, Permission.UpdateReservation),
            new(ApplicationRole.Manager, Permission.GetAllUsers),
            new(ApplicationRole.Manager, Permission.DeleteOwnAccount),
            new(ApplicationRole.Manager, Permission.OpenAdministrationPage),
            new(ApplicationRole.Manager, Permission.CanSeeAdministrativeContent),
            new(ApplicationRole.Manager, Permission.GetWorkoutTypes),

            new(ApplicationRole.Member, Permission.GetRealWorkoutDetails),
            new(ApplicationRole.Member, Permission.GetOwnReservations),
            new(ApplicationRole.Member, Permission.GetOwnReservationDetails),
            new(ApplicationRole.Member, Permission.CreateReservation),
            new(ApplicationRole.Member, Permission.CancelReservation),
            new(ApplicationRole.Member, Permission.DeleteOwnAccount),
        };
    }
}

