using WorkoutReservation.Domain.Entities.Workout;

namespace WorkoutReservation.Infrastructure.Seeders
{
    internal class DummyParticularWorkouts
    {
        internal static List<ParticularWorkout> GetWorkouts()
        {
            var particularWorkouts = new List<ParticularWorkout>
            {
                new ParticularWorkout()
                {
                    StartTime = new TimeOnly(10, 15),
                    EndTime = new TimeOnly(11, 00),
                    Date = new DateOnly(2022, 01, 01),
                    MaxParticipianNumber = 10,
                    CurrentParticipianNumber = 4,
                    CreatedBy = "Dummy Admin",
                    CreatedDate = DateTime.Now,
                    IsAutoGenerated = false
                },

                new ParticularWorkout()
                {
                    StartTime = new TimeOnly(20, 15),
                    EndTime = new TimeOnly(21, 00),
                    Date = new DateOnly(2022, 05, 05),
                    MaxParticipianNumber = 15,
                    CurrentParticipianNumber = 8,                      
                    CreatedDate = DateTime.Now,
                    IsAutoGenerated = true
                },
            };

            return particularWorkouts;
        }

    }
}
