using System.Text.Json.Serialization;
using WorkoutReservation.Domain.Enums;

namespace WorkoutReservation.Application.Features.RealWorkouts.Queries.GetRealWorkoutDetail;

public class RealWorkoutDetailDto
{
    public int Id { get; set; }
    public int CurrentParticipiantNumber { get; set; }
    public int MaxParticipiantNumber { get; set; }
    public TimeOnly StartTime { get; set; }
    public TimeOnly EndTime { get; set; }
    public DateOnly Date { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedDate { get; set; }
    public string LastModifiedBy { get; set; }
    public DateTime? LastModifiedDate { get; set; }
    public WorkoutTypeForRealWorkoutDetailDto WorkoutType { get; set; }
    public InstructorForRealWorkoutDetailDto Instructor { get; set; }
}

public class WorkoutTypeForRealWorkoutDetailDto
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public WorkoutIntensity Intensity { get; set; }
}

public class InstructorForRealWorkoutDetailDto
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
}
