using WorkoutReservation.Application.Common.Models;

namespace WorkoutReservation.Application.Features.RealWorkouts.Queries.GetRealWorkoutDetail
{
    public class RealWorkoutDetailDto
    {
        public int Id { get; set; }
        public int MaxParticipianNumber { get; set; }
        public TimeOnly StartTime { get; set; }
        public TimeOnly EndTime { get; set; }

        public WorkoutTypeDto WorkoutType { get; set; }
        public int? WorkoutTypeId { get; set; }

        public InstructorDto Instructor { get; set; }
        public int? InstructorId { get; set; }

        public DateOnly Date { get; set; }
        public int CurrentParticipianNumber { get; set; }
        public bool IsAutoGenerated { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
    }
}
