using MediatR;
using Quartz;
using WorkoutReservation.Application.Features.RepetitiveWorkouts.Commands.GenerateUpcomingWorkouts;

namespace WorkoutReservation.Infrastructure.BackgroundJobs;

public class GenerateUpcomingWorkoutsExecutor : IJob
{
    private readonly IMediator _mediator;

    public GenerateUpcomingWorkoutsExecutor(IMediator mediator)
    {
        _mediator = mediator;
    }
    
    public async Task Execute(IJobExecutionContext context)
    {
        await _mediator.Send(new GenerateUpcomingWorkoutsCommand(IsAutoGenerated: true));
    }
}